/* @generated by scripts/export_signal_client_brain.mjs. Do not edit by hand. */
#ifndef SIGNAL_CLIENT_STRATEGIC_H
#define SIGNAL_CLIENT_STRATEGIC_H

#include <stddef.h>

#define SIGNAL_CLIENT_STRATEGIC_LAYER_COUNT 4u
#define SIGNAL_CLIENT_STRATEGIC_INPUT_COUNT 78u
#define SIGNAL_CLIENT_STRATEGIC_OUTPUT_COUNT 1u
#define SIGNAL_CLIENT_STRATEGIC_HIDDEN0 32u
#define SIGNAL_CLIENT_STRATEGIC_HIDDEN1 16u

extern const char *const signal_client_strategic_checkpoint_hash;
extern const char *const signal_client_strategic_feature_set;
extern const unsigned signal_client_strategic_feature_encoder_version;

float signal_client_strategic_score(const float features[78]);
int signal_client_strategic_select_best(const float *features,
                                 size_t candidate_count,
                                 float *scores_out);

#endif /* SIGNAL_CLIENT_STRATEGIC_H */
