/* @generated by scripts/export_signal_client_brain.mjs. Do not edit by hand. */
#ifndef SIGNAL_CLIENT_FLIGHT_H
#define SIGNAL_CLIENT_FLIGHT_H

#include <stddef.h>

#define SIGNAL_CLIENT_FLIGHT_LAYER_COUNT 4u
#define SIGNAL_CLIENT_FLIGHT_INPUT_COUNT 48u
#define SIGNAL_CLIENT_FLIGHT_OUTPUT_COUNT 1u
#define SIGNAL_CLIENT_FLIGHT_HIDDEN0 32u
#define SIGNAL_CLIENT_FLIGHT_HIDDEN1 16u

extern const char *const signal_client_flight_checkpoint_hash;
extern const char *const signal_client_flight_feature_set;
extern const unsigned signal_client_flight_feature_encoder_version;

float signal_client_flight_score(const float features[48]);
int signal_client_flight_select_best(const float *features,
                                 size_t candidate_count,
                                 float *scores_out);

#endif /* SIGNAL_CLIENT_FLIGHT_H */
