/* @generated by scripts/export_signal_client_brain.mjs. Do not edit by hand. */
#ifndef SIGNAL_CLIENT_TACTICAL_H
#define SIGNAL_CLIENT_TACTICAL_H

#include <stddef.h>

#define SIGNAL_CLIENT_TACTICAL_LAYER_COUNT 4u
#define SIGNAL_CLIENT_TACTICAL_INPUT_COUNT 70u
#define SIGNAL_CLIENT_TACTICAL_OUTPUT_COUNT 1u
#define SIGNAL_CLIENT_TACTICAL_HIDDEN0 32u
#define SIGNAL_CLIENT_TACTICAL_HIDDEN1 16u

extern const char *const signal_client_tactical_checkpoint_hash;
extern const char *const signal_client_tactical_feature_set;
extern const unsigned signal_client_tactical_feature_encoder_version;

float signal_client_tactical_score(const float features[70]);
int signal_client_tactical_select_best(const float *features,
                                 size_t candidate_count,
                                 float *scores_out);

#endif /* SIGNAL_CLIENT_TACTICAL_H */
