#!/usr/bin/env python3
"""Generate Signal's frozen HNN confidence thresholds from replay controls."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import subprocess
import sys
from pathlib import Path
from typing import Any

from hnn_null_corpus import (
    CORPUS_NAME,
    CORPUS_VERSION,
    GENERATOR_VERSION,
    materialize,
    null_scenarios,
    positive_scenarios,
)


BACKENDS = ("builtin", "direct", "radix2")
EXPECTED_NAMES = {
    "builtin": "builtin-radix2",
    "direct": "lecore-direct",
    "radix2": "lecore-radix2",
}
MIN_SCORE_FLOOR = 0.70
MIN_MARGIN_FLOOR = 0.25
MAX_CAPACITY_LOAD = 1.0
MAX_HELD_OUT_FALSE_CONFIDENCE_RATE = 0.01


def accepted(sample: dict[str, Any], min_score: float, min_margin: float) -> bool:
    return (
        int(sample["stored_count"]) > 0
        and float(sample["capacity_load"]) <= MAX_CAPACITY_LOAD
        and math.isfinite(float(sample["top_allowed_score"]))
        and math.isfinite(float(sample["allowed_margin"]))
        and float(sample["top_allowed_score"]) >= min_score
        and float(sample["allowed_margin"]) >= min_margin
    )


def threshold_for(samples: list[dict[str, Any]]) -> tuple[float, float]:
    training = [sample for sample in samples if not sample["held_out"]]
    min_score = MIN_SCORE_FLOOR
    min_margin = MIN_MARGIN_FLOOR
    passing = [
        sample for sample in training
        if accepted(sample, min_score, min_margin)
    ]
    if passing:
        min_score = max(float(sample["top_allowed_score"]) for sample in passing)
        min_score += 0.000001
    return min_score, min_margin


def contract_from(report: dict[str, Any]) -> dict[str, Any]:
    samples = report["samples"]
    if not samples:
        raise RuntimeError("null corpus is empty")
    contract = samples[0]["contract"]
    if any(sample["contract"] != contract for sample in samples):
        raise RuntimeError("null corpus contains more than one HNN contract")
    return contract


def header_text(artifact: dict[str, Any]) -> str:
    contract = artifact["contract"]
    thresholds = artifact["thresholds"]
    return f"""/* Generated by scripts/calibrate_hnn_confidence.py. Do not edit by hand. */
#ifndef HOLOGRAPHIC_NN_CALIBRATION_DATA_H
#define HOLOGRAPHIC_NN_CALIBRATION_DATA_H

#define HNN_CALIBRATION_ARTIFACT_VERSION {artifact['artifact_version']}u
#define HNN_CALIBRATION_CORPUS_VERSION {artifact['corpus']['version']}u
#define HNN_CALIBRATION_GENERATOR_VERSION {artifact['corpus']['generator_version']}u
#define HNN_CALIBRATION_CONTRACT_VERSION {contract['contract_version']}u
#define HNN_CALIBRATION_DIMENSION {contract['dimension']}
#define HNN_CALIBRATION_CONTRACT_SEED 0x{contract['seed']}ull
#define HNN_CALIBRATION_KEYGEN_VERSION {contract['keygen_version']}u
#define HNN_CALIBRATION_ENCODER_VERSION {contract['encoder_version']}u
#define HNN_CALIBRATION_TRACE_FORMAT_VERSION {contract['trace_format_version']}u
#define HNN_CALIBRATION_TRACE_CAPACITY {contract['trace_capacity']}u
#define HNN_CALIBRATION_ACTION_VOCABULARY_HASH 0x{contract['action_vocabulary_hash']}ull

#define HNN_CALIBRATION_BUILTIN_MIN_SCORE {thresholds['builtin-radix2']['min_score']:.9f}f
#define HNN_CALIBRATION_BUILTIN_MIN_MARGIN {thresholds['builtin-radix2']['min_margin']:.9f}f
#define HNN_CALIBRATION_DIRECT_MIN_SCORE {thresholds['lecore-direct']['min_score']:.9f}f
#define HNN_CALIBRATION_DIRECT_MIN_MARGIN {thresholds['lecore-direct']['min_margin']:.9f}f
#define HNN_CALIBRATION_RADIX2_MIN_SCORE {thresholds['lecore-radix2']['min_score']:.9f}f
#define HNN_CALIBRATION_RADIX2_MIN_MARGIN {thresholds['lecore-radix2']['min_margin']:.9f}f
#define HNN_CALIBRATION_MAX_CAPACITY_LOAD {MAX_CAPACITY_LOAD:.9f}f

#endif /* HOLOGRAPHIC_NN_CALIBRATION_DATA_H */
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    for backend in BACKENDS:
        parser.add_argument(f"--{backend}", required=True, type=Path)
    parser.add_argument("--artifact", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify existing files instead of writing them",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        binaries = {name: getattr(args, name).resolve() for name in BACKENDS}
        null_reports = {
            name: materialize(binary, null_scenarios())
            for name, binary in binaries.items()
        }
        positive_reports = {
            name: materialize(binary, positive_scenarios())
            for name, binary in binaries.items()
        }
        contracts = {name: contract_from(report) for name, report in null_reports.items()}
        if len({json.dumps(value, sort_keys=True) for value in contracts.values()}) != 1:
            raise RuntimeError("HNN backends did not report one shared contract")

        threshold_rows: dict[str, Any] = {}
        held_out_total = 0
        held_out_false = 0
        positive_total = 0
        positive_accepted = 0
        for short_name in BACKENDS:
            report = null_reports[short_name]
            backend_name = report["backend"]
            if backend_name != EXPECTED_NAMES[short_name]:
                raise RuntimeError(
                    f"{short_name} binary reported unexpected backend {backend_name}"
                )
            samples = report["samples"]
            min_score, min_margin = threshold_for(samples)
            training = [sample for sample in samples if not sample["held_out"]]
            held_out = [sample for sample in samples if sample["held_out"]]
            training_false = sum(
                accepted(sample, min_score, min_margin) for sample in training
            )
            held_false = sum(
                accepted(sample, min_score, min_margin) for sample in held_out
            )
            positives = positive_reports[short_name]["samples"]
            positive_pass = sum(
                accepted(sample, min_score, min_margin) for sample in positives
            )
            runtime_false = sum(
                bool(sample["confidence"]["accepted"]) for sample in samples
            )
            overloaded = [
                sample for sample in samples
                if sample["category"] == "overloaded-memory"
            ]
            if runtime_false != training_false + held_false:
                raise RuntimeError(
                    f"{backend_name} runtime gate disagrees with generated thresholds"
                )
            if any(
                sample["confidence"]["reason"] != "capacity"
                for sample in overloaded
            ):
                raise RuntimeError(
                    f"{backend_name} did not reject every overloaded trace by capacity"
                )
            runtime_positive = sum(
                bool(sample["confidence"]["accepted"]) for sample in positives
            )
            if runtime_positive != positive_pass:
                raise RuntimeError(
                    f"{backend_name} runtime gate disagrees on matched controls"
                )
            held_out_total += len(held_out)
            held_out_false += held_false
            positive_total += len(positives)
            positive_accepted += positive_pass
            threshold_rows[backend_name] = {
                "held_out_false_confident": held_false,
                "held_out_samples": len(held_out),
                "min_margin": min_margin,
                "min_score": min_score,
                "positive_controls_accepted": positive_pass,
                "positive_controls_total": len(positives),
                "training_false_confident": training_false,
                "training_samples": len(training),
            }
        held_rate = held_out_false / held_out_total if held_out_total else 1.0
        if held_rate > MAX_HELD_OUT_FALSE_CONFIDENCE_RATE:
            raise RuntimeError(
                f"held-out false-confidence rate {held_rate:.4%} exceeds 1%"
            )
        if positive_accepted == 0:
            raise RuntimeError("calibration rejects every matched-trace control")

        contract = next(iter(contracts.values()))
        corpus_digest = hashlib.sha256(
            "".join(
                null_reports[name]["sample_digest"] for name in BACKENDS
            ).encode()
        ).hexdigest()
        artifact = {
            "artifact_version": 1,
            "contract": {
                "action_vocabulary_hash": contract["action_vocabulary_hash"],
                "backend_names": [EXPECTED_NAMES[name] for name in BACKENDS],
                "contract_version": 1,
                "dimension": contract["dim"],
                "encoder_version": contract["encoder_version"],
                "keygen_version": contract["keygen_version"],
                "seed": contract["seed"],
                "trace_capacity": 128,
                "trace_format_version": contract["trace_format_version"],
            },
            "corpus": {
                "category_counts": null_reports["builtin"]["category_counts"],
                "digest": corpus_digest,
                "generator_version": GENERATOR_VERSION,
                "name": CORPUS_NAME,
                "scenario_digest": null_reports["builtin"]["scenario_digest"],
                "version": CORPUS_VERSION,
            },
            "fixed_during_run": True,
            "gates": {
                "held_out_false_confidence_rate": held_rate,
                "held_out_limit": MAX_HELD_OUT_FALSE_CONFIDENCE_RATE,
                "held_out_passed": held_rate <= MAX_HELD_OUT_FALSE_CONFIDENCE_RATE,
                "over_capacity_always_rejected": True,
                "positive_controls_accepted": positive_accepted,
                "positive_controls_total": positive_total,
            },
            "max_capacity_load": MAX_CAPACITY_LOAD,
            "schema": "signal.hnn_confidence_calibration.v1",
            "thresholds": threshold_rows,
        }
        artifact_bytes = (
            json.dumps(artifact, indent=2, sort_keys=True) + "\n"
        ).encode()
        header_bytes = header_text(artifact).encode()
        if args.check:
            if args.artifact.read_bytes() != artifact_bytes:
                raise RuntimeError(f"calibration artifact is stale: {args.artifact}")
            if args.header.read_bytes() != header_bytes:
                raise RuntimeError(f"calibration header is stale: {args.header}")
            print(
                f"HNN calibration is current; held-out false confidence "
                f"{held_rate:.2%}"
            )
        else:
            args.artifact.parent.mkdir(parents=True, exist_ok=True)
            args.header.parent.mkdir(parents=True, exist_ok=True)
            args.artifact.write_bytes(artifact_bytes)
            args.header.write_bytes(header_bytes)
            print(
                f"HNN calibration written; held-out false confidence "
                f"{held_rate:.2%}"
            )
        return 0
    except (OSError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"HNN calibration failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
